# Generated by Django 4.2.1 on 2023-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_alter_customerfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
