# Generated by Django 4.2.1 on 2023-08-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_alter_customerfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
